notifications:
    on_success: never
    on_failure: never

os :
  - linux

dist:
  - xenial

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install pybullet"
  - "pip install numpy"
  - "python setup.py install"

script:
  - cd tests
  - python test_launcher.py
